name: My first CI/CD pipeline
on:
 # push:
 #     branches:
 #    -  main
  #schedule:
   # - cron: "5 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  job1:
    name: job1
    needs: job2
    runs-on: ubuntu-latest      #Github hosted runner
    steps:
      - name: Running command job1
        run: echo "Hello world"
      - name: Check os-release job1
        run: cat /etc/os-release
      - name: sleeping job1
        run: sleep 5

  job2:
    name: job2 Upload artifacts
    runs-on: macos-14     #Github hosted runner
    steps:
    - name: Running command sleeping mode job2
      run: |
        echo "Hello world job2"
        ls -ltr
        hostname    
   
    - name:  chcekout
      uses: actions/checkout@v4
 
    - name: validate
      run: |
        echo ls -ltr  >> myArtifact.txt
        mkdir artifacts/
        echo "This is file1" > artifacts/file1.txt
        echo "This is file2" > artifacts/file2.txt
        
        hostname > artifacts/hostname.txt
        
        ls -ltr
        ls -ltr artifacts

    - name: Upload Single file
      uses: actions/upload-artifact@v5.0.0
      with:
         name: single_file
         path: ./myArtifact.txt
   
    -  name: Upload from directory
       uses: actions/upload-artifact@v5.0.0

       with:
         name: directory_artifacts
         path: artifacts/
    -  name: List files from directory
       run: ls -ltr
       
    -  name: Upload from multiple paths
       uses: actions/upload-artifact@v5.0.0
       with:
         name: multiple_paths
         path: |
           ./myArtifact.txt
            artifacts/

    - name: Upload from multiple paths with exclusions
      uses: actions/upload-artifact@v5.0.0
      with:
        name: multiple_paths_with_exclusions
        path: |
          ./myArtifact.txt
          artifacts/
          !**/hostname.txt
  job3:		       
     name: download artifcats job3
     runs-on: ubuntu-latest
     steps:
       - name: Downlaod artifcats
         uses: actions/download-artifact@v5.0.0
         with:
          name: single_file
          path: ./myArtifact.txt
         
    
        
