name: My first CI/CD pipeline
on:
  push:
      branches:
      -  main
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest      #Github hosted runner
    steps:
      - name: Running command
        run: echo "Hello world"
      - name: Check os-release
        run: cat /etc/os-release
      - name: sleeping
        run: sleep 20

  job2:
    name: job2
    runs-on: ubuntu-latest      #Github hosted runner
    steps:
      - name: Running command sleeping mode job2
        run: sleep 50
        run: echo "Hello world job2"
      - 

    
